# Generated by Django 2.1.2 on 2018-10-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(blank=True, max_length=200, null=True)),
                ('nfl', models.CharField(blank=True, max_length=3, null=True)),
                ('week', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=2, null=True)),
                ('plays', models.IntegerField(blank=True, null=True)),
                ('fpts', models.IntegerField(blank=True, null=True)),
                ('gp', models.IntegerField(blank=True, null=True)),
                ('fpts_per_game', models.IntegerField(blank=True, null=True)),
                ('run', models.IntegerField(blank=True, null=True)),
                ('ryd', models.IntegerField(blank=True, null=True)),
                ('rtd', models.IntegerField(blank=True, null=True)),
                ('pass_count', models.IntegerField(blank=True, null=True)),
                ('cmp', models.IntegerField(blank=True, null=True)),
                ('pyds', models.IntegerField(blank=True, null=True)),
                ('fum', models.IntegerField(blank=True, null=True)),
                ('fg', models.IntegerField(blank=True, null=True)),
                ('fg_miss', models.IntegerField(blank=True, null=True)),
                ('xpt', models.IntegerField(blank=True, null=True)),
                ('xpt_miss', models.IntegerField(blank=True, null=True)),
                ('team_defense', models.IntegerField(blank=True, null=True)),
                ('sack', models.IntegerField(blank=True, null=True)),
                ('fr', models.IntegerField(blank=True, null=True)),
                ('int', models.IntegerField(blank=True, null=True)),
                ('td', models.IntegerField(blank=True, null=True)),
                ('sfty', models.IntegerField(blank=True, null=True)),
                ('ryda', models.IntegerField(blank=True, null=True)),
                ('pyda', models.IntegerField(blank=True, null=True)),
                ('tyda', models.IntegerField(blank=True, null=True)),
                ('tkls', models.IntegerField(blank=True, null=True)),
                ('solo', models.IntegerField(blank=True, null=True)),
                ('asst', models.IntegerField(blank=True, null=True)),
                ('sacks', models.IntegerField(blank=True, null=True)),
                ('ff', models.IntegerField(blank=True, null=True)),
                ('rf', models.IntegerField(blank=True, null=True)),
                ('pd', models.IntegerField(blank=True, null=True)),
                ('krtn', models.IntegerField(blank=True, null=True)),
                ('kryd', models.IntegerField(blank=True, null=True)),
                ('kavg', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('klng', models.IntegerField(blank=True, null=True)),
                ('ktd', models.IntegerField(blank=True, null=True)),
                ('prtn', models.IntegerField(blank=True, null=True)),
                ('pryd', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('pavg', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('plng', models.IntegerField(blank=True, null=True)),
                ('ptd', models.IntegerField(blank=True, null=True)),
                ('pfc', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'player_stat',
            },
        ),
    ]
